version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    environment:
      PATH: $HOME/:deno/bin:$PATH
    steps:
      - checkout
      - run:
          name: Install Deno
          command: |
            apt-get install curl
            curl -fsSL https://deno.land/x/install/install.sh | bash -s -- v0.13.0
      - run:
          name: Run Tests
          command: deno -A test.ts