name: CI
on:
  push:
    branches:
      - "**"      
  pull_request:
    types:
      - labeled
jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'CI start')
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
    steps:
      - uses: actions/checkout@v1
      - name: Install Deno
        run: |
          DENO_VERSION=$(cat .denov)
          curl -fsSL https://deno.land/x/install/install.sh | bash -s -- ${DENO_VERSION}
      - name: Run Tests
        run: |
          export PATH=$HOME/.local/bin:$PATH
          deno test -A
