name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.x]
        redis: [6.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Check mod.ts
        run: |
          deno run --allow-read --allow-write tools/make_mod.ts
          git diff --exit-code

      - name: Run lint
        run: |
          deno fmt --check
          deno lint --unstable

      - name: Set up Redis ${{ matrix.redis }}
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: "false"

      - name: Run tests
        run: |
          deno test -A redis_test.ts
