name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis: [6.2]

    steps:
      - uses: actions/checkout@v2

      - name: Get Deno version
        run: |
          echo "DENO_VERSION=$(cat .denov)" >> $GITHUB_ENV

      - name: Set up Deno ${{ env.DENO_VERSION }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Check mod.ts
        run: |
          deno run --allow-read --allow-write --allow-run tools/make_mod.ts
          git diff --exit-code

      - name: Run lint
        run: |
          deno fmt --check --ignore=./benchmark/node_modules
          deno lint --unstable --ignore=./benchmark/node_modules

      - name: Set up Redis ${{ matrix.redis }}
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis }}
          auto-start: "true"

      - name: Run tests
        run: |
          deno test -A redis_test.ts
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: benchmark
      - name: Run benchmarks
        working-directory: benchmark
        run: |
          deno bundle benchmark.ts > benchmark.js
          deno run -A deno-redis.ts
          node ioredis.js
