name: Bump

on:
  push:
    branches:
      - ci-test
  schedule:
    - cron: 0 13 * * *    
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
    steps:
    - uses: actions/checkout@v1
    - uses: keroxp/dink-bot@master
      with:
        github-repository: ${{ github.repository }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
